services:
  app:
    container_name: fooder-app
    build:
      context: ./app

  origin:
    container_name: fooder-origin
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=localhost
