services:
  api:
    container_name: fooder-api
    build:
      context: ./api

  origin:
    container_name: fooder-origin
    build:
      context: ./nginx
    depends_on:
      - api
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=localhost

  fooder-db:
    container_name: fooder-db
    image: postgres:15-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fooder
