services:
  api:
    container_name: fooder-api
    build:
      context: ./api

  origin:
    container_name: fooder-origin
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=localhost
