openapi: 3.0.4
info:
  title: 'Meals API'
  description: 'API for family meals management'
  contact:
    email: 'benditdev90@gmail.com'
    name: 'Owner'
  version: '1.0.0'
servers:
  - url: 'https://fooder.bendit.dev/api/v1'
tags:
  - name: 'recipe'
paths:
  /recipes:
    get:
      description: 'Returns a collection of recipes'
      operationId: 'getRecipes'
      tags: ['recipe']
      responses:
        '200':
          description: 'A collection of recipes'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      description: 'Creates new recipe'
      operationId: 'createRecipe'
      tags: ['recipe']
      responses:
        '201':
          description: 'Recipe created'
          headers:
            Location:
              descripton: location of newly created resource
              schema:
                type: string
                example: '/recipes/1'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/NotAuthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /recipes/{id}:
    get:
      description: 'Returns a recipe resource'
      operationId: 'getRecipeByID'
      tags: ['recipe']
      responses:
        '200':
          description: 'A recipe resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: 'Invalid request payload or query params'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemJsonDetails'

    NotAuthenticated:
      description: 'User did not authenticate, login or valid api key required'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemJsonDetails'

    Forbidden:
      description: 'User is not authorized to perfom the operation'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemJsonDetails'

    NotFound:
      description: 'Requested resource was not found'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemJsonDetails'

    InternalServerError:
      description: 'Unexpected server error occurred'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemJsonDetails'

  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    RecipeIngredient:
      type: object
      properties:
        ingredientId:
          type: string
        name:
          type: string
    Recipe:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        description:
          type: string
    ProblemJsonDetails:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

